
FROM python:3.12-slim


RUN apt-get update && apt-get install -y \
    git \
    curl \
    jq \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# --- Medusa ---
RUN pip install --no-cache-dir medusa-security

# --- Directorio de trabajo ---
WORKDIR /scan

# --- Script principal ---
COPY script/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]